version: '3'
services:
  cortex-js:
    build: ./cortex-js
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/database
    volumes:
      - ./cortex-js:/app

  cortex-cpp:
    build: ./cortex-cpp
    ports:
      - "3001:3001"
    depends_on:
      - cortex-js
    environment:
      - GPU_ENABLED=true
      - GPU_FAMILY=Nvidia
      - CPU_INSTRUCTIONS=AVX2

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: