name: "\U0001F929 Model Request"
description: "Request a new model to be compiled"
title: 'feat: [DESCRIPTION]'
labels: 'type: model request'
body:
  - type: markdown
    attributes:
      value: "**Tip:** Download any model with `cortex pull HUGGINGFACE_MODEL_ID`. Use this form for unsupported models only."
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Model Requests"
      description: "If applicable, include the source URL, licenses, and any other relevant information"
  - type: checkboxes
    attributes:
      label: "Which formats?"
      options:
        - label: GGUF (llama.cpp)
        - label: TensorRT (TensorRT-LLM)
        - label: ONNX (Onnx Runtime)
