name: Build and Push Docker image to Azure Container Registry

on:
  push:
    branches: [main]

env:
  REGISTRY_NAME: janresearch.azurecr.io
  IMAGE_NAME: inference_backend

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Extract commit short SHA
        id: extract_commit_id
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}-${{ steps.extract_commit_id.outputs.sha_short }}
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.extract_branch.outputs.branch }}-latest