name: CI test for platform
on:
  pull_request:
    paths:
      - "platform/**"
      - .github/workflows/platform-quality-gate.yml
  workflow_dispatch:
jobs:
  build-and-publish-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install && yarn build
        working-directory: ./platform
      - run: yarn test
        name: run tests
        working-directory: ./platform
